# Generated by Django 5.1 on 2024-08-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_views',
            field=models.IntegerField(default=0),
        ),
    ]
